# -*- coding: utf-8 -*-
"""mitre-extracct.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKiIuGDKwmXNqhfFUr39AGDJkjWdQPTV
"""

import json

# Commented out IPython magic to ensure Python compatibility.
from mitreattack.stix20 import MitreAttackData

#! wget https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
# %pip install -q mitreattack-python

mitre_attack_data = MitreAttackData("enterprise-attack.json")

groups = [
    {"id": g.id, "name": g.name}
    for g in mitre_attack_data.get_groups()
    if g.name.startswith("APT")
]


def techniques_of_group(gid):
    return [
        ref.external_id
        for technique in mitre_attack_data.get_techniques_used_by_group(gid)
        for ref in technique["object"].external_references
        if ref.source_name == "mitre-attack"
    ]


def remove_sub_techniques(tx):
    return list(set((t.split(".")[0] for t in tx)))


groups_with_techniques = [
    {"techniques": remove_sub_techniques(techniques_of_group(g["id"])), **g}
    for g in groups
]

tactics = [
    {
        "x_mitre_shortname": tac["x_mitre_shortname"],
        "name": tac["name"],
        "id": tac["external_references"][0]["external_id"],
    }
    for tac in mitre_attack_data.get_tactics_by_matrix()["Enterprise ATT&CK"]
]


def techniques_of_tactic(shortname):
    return [
        {"name": technique.name, "id": technique.external_references[0].external_id}
        for technique in mitre_attack_data.get_techniques_by_tactic(
            tactic_shortname=shortname,
            domain="enterprise-attack",
            remove_revoked_deprecated=True,
        )
    ]


def filter_sub_techniques(tx):
    return [t for t in tx if not "." in t["id"]]


techniques_by_tactics = {
    tactic["id"]: filter_sub_techniques(
        techniques_of_tactic(tactic["x_mitre_shortname"])
    )
    for tactic in tactics
}

matrix = {
    "groups_with_techniques": groups_with_techniques,
    "tactics": tactics,
    "techniques_by_tactics": techniques_by_tactics,
}

with open("matrix.json", "w") as f:
    json.dump(matrix, f)

# Run this code to get the number of techniques per tactic (all_ttps.json)
results = {}
for tactic in techniques_by_tactics:
    for technique in techniques_by_tactics[tactic]:
        results[f"{tactic}/{technique['id']}"] = 0
with open("all_ttps.json", "w") as f:
    json.dump(results, f, indent=4)
