apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: gai-cti-docs
  namespace: gai-cti-docs-project
spec:
  source:
    type: Binary   # indicates binary upload
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: gai-cti-docs:latest
  triggers:
    - type: ConfigChange   # rebuilds when BuildConfig changes
    - type: ImageChange    # rebuilds when base image changes
