free_connectors_list = set(
    (
        "alienvault",
        "threatfox",
        "urlhaus",
        "urlhaus-recent-payloads",
        "malwarebazaar",
        "malwarebazaar-recent-additions",
        "abuseipdb-ipblacklist",
        "stopforumspam",
        "shadowserver",
        "cisa-known-exploited-vulnerabilities",
        "crtsh",
        "misp-feed",
        "misp",
        "vxvault",
        "cve",
        "mitre",
        "mitre-atlas",
        "disarm-framework",
    )
)


connector_dir2connector_name = {
    "misp": "MISP",
    "tenable-security-center": "Tenable Security Center",
    "threatmatch": "ThreatMatch",
    "catalyst": "CATALYST",
    "tweetfeed": "Tweetfeed",
    "email-intel-microsoft": "Email Intel Microsoft",
    "crowdstrike": "CrowdStrike",
    "google-drive": "Google Drive",
    "ipsum": "IPsum",
    "rst-threat-feed": "RST Threat Feed",
    "greynoise-feed": "GreyNoiseFeed",
    "stopforumspam": "Stopforumspam",
    "group-ib": "Group-IB Connector",
    "mandiant": "Mandiant",
    "cape": "CAPE",
    "restore-files": "RestoreFiles",
    "riskiq": "RISKIQ",
    "vulncheck": "VulnCheck Connector",
    "stream-importer": "StreamImporterConnector",
    "s3": "S3 Bucket",
    "malwarebazaar": "MalwareBazaar",
    "google-ti-feeds": "Google Threat Intel Feeds",
    "misp-feed": "MISP Feed",
    "cofense": "CofenseIntel",
    "spycloud": "SpyCloud",
    "microsoft-sentinel-incidents": "Microsoft Sentinel Incidents",
    "opencti": "OpenCTI Datasets",
    "cuckoo": "cuckoo",
    "intel471": "Intel471",
    "virustotal-livehunt-notifications": "VirusTotal Livehunt Notifications",
    "recorded-future": "Recorded Future",
    "wiz": "Wiz Cloud Threat LandScape",
    "valhalla": "Valhalla",
    "lia-file-feed": "Loader Insight Agency File Feed",
    "cisa-known-exploited-vulnerabilities": "CISA Known Exploited Vulnerabilities",
    "luminar": "Luminar",
    "cisco-sma": "CISCO-SMA",
    "mitre-atlas": "MITRE ATLAS",
    "threatfox": "Abuse.ch | ThreatFox",
    "dogesec-vulmatch": "VULMATCH",
    "zvelo": "Zvelo",
    "microsoft-defender-incidents": "Microsoft Defender Incidents",
    "sentinel-incidents": "Microsoft Sentinel",
    "sekoia": "SEKOIA.IO",
    "servicenow": "ServiceNow",
    "alienvault": "AlienVault",
    "orange-cyberdefense": "Orange Cyberdefense Cyber Threat Intelligence",
    "infoblox": "INFOBLOX",
    "harfanglab-incidents": "Harfanglab Incidents Connector",
    "malpedia": "Malpedia",
    "taxii2": "TAXII2",
    "phishunt": "Phishunt",
    "eset": "ESET Cyber Threat Intelligence",
    "cofense-threathq": "Cofense-ThreatHQ",
    "urlhaus-recent-payloads": "URLhaus Recent Payloads",
    "cyber-campaign-collection": "APT & Cybercriminals Campaign Collection",
    "cluster25": "Cluster25",
    "dogesec-stixify": "Stixify",
    "dogesec-obstracts": "Obstracts",
    "mitre": "MITRE Datasets",
    "red-flag-domains": "Red Flag Domains",
    "cve": "Common Vulnerabilities and Exposures",
    "crits": "CRITs",
    "tenable-vuln-management": "Tenable Vuln Management",
    "cybersixgill": "Cybersixgill Darkfeed",
    "dragos": "Dragos",
    "ransomwarelive": "Ransomware Connector",
    "socprime": "SOC Prime",
    "disarm-framework": "DISARM Framework",
    "fortinet-ti": "FORTINET-TI",
    "malcore": "Malcore",
    "rst-report-hub": "RST Report Hub",
    "bambenek": "Bambenek",
    "maltiverse": "MALTIVERSE",
    "ironnet": "IronNet threat intel",
    "nti": "NTI",
    "urlhaus": "Abuse.ch URLhaus",
    "accenture-acti": "Accenture ACTI",
    "diode-import": "Diode Import",
    "abuseipdb-ipblacklist": "AbuseIPDB IP Blacklist",
    "comlaude": "Comlaude",
    "proofpoint-et-reputation": "ProofPoint ET Reputation",
    "shadowserver": "Shadowserver",
    "email-intel-imap": "Email Intel IMAP",
    "mwdb": "MWDB connector",
    "crtsh": "crtsh",
    "zerofox": "Zerofox",
    "cpe": "Common Platform Enumeration",
    "proofpoint-tap": "ProofPointTAP",
    "sentinelone-incidents": "SentinelOne Incident External Import Connector",
    "dogesec-ctibutler": "CTIBUTLER",
    "disinfox": "DISINFOX Connector",
    "malwarebazaar-recent-additions": "MalwareBazaar Recent Additions",
    "vxvault": "VX Vault URL list",
    "kaspersky": "Kaspersky",
    "citalid": "Citalid",
    "thehive": "TheHive",
    "sentinelone-threats": "SentinelOne Threats",
    "silobreaker": "Silobreaker Cyber Threat Intelligence",
    "lastinfosec": "lastinfosec-CTI",
    "intel471_v2": "Intel471",
    "anyrun-feed": "ANY.RUN feed",
    "urlscan": "Urlscan",
    "chapsvision": "Chapsvision",
    "abuse-ssl": "Abuse.ch SSL Blacklist",
    "doppel": "Doppel Threat Intelligence",
    "flashpoint": "Flashpoint",
    "opencsam": "OpenCSAM",
    "intelfinder": "intelfinder",
    "feedly": "Feedly",
    "tanium-incidents": "Tanium Threat Response Incidents",
}

free_connector_names = set(
    (
        "Stopforumspam",
        "CISA Known Exploited Vulnerabilities",
        "Abuse.ch | ThreatFox",
        "First EPSS Connector",
        "External Import First EPSS Connector",
        "DISARM Framework",
        "MITRE Datasets",
        "MISP",
        "AlienVault",
        "AbuseIPDB IP Blacklist",
        "VX Vault URL list",
        "MISP Feed",
        "Common Vulnerabilities and Exposures",
        "MITRE ATLAS",
        "MalwareBazaar",
    )
)
